import { updateUserRole } from "@/app/dashboard/admin/actions";
import { EmptyState } from "@/components/app/empty-state";
import { MessageBanner } from "@/components/app/message-banner";
import { SubmitButton } from "@/components/forms/submit-button";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { requireRole } from "@/lib/auth/guards";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const metadata = { title: "Users" };
export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string; q?: string }> }) { const params = await searchParams; await requireRole(["admin"]); const supabase = await createServerSupabaseClient(); let query = supabase.from("profiles").select("*").order("created_at", { ascending: false }); if (params.q) query = query.or(`email.ilike.%${params.q}%,full_name.ilike.%${params.q}%`); const { data: users, error } = await query; return <div className="space-y-6"><div><h1 className="text-3xl font-bold">User management</h1><p className="mt-2 text-muted-foreground">Search users and manage roles through Supabase RLS.</p></div><MessageBanner error={params.error} message={params.message} /><form className="flex gap-2"><input className="flex h-11 w-full rounded-xl border border-input bg-background/60 px-3 py-2 text-sm" defaultValue={params.q ?? ""} name="q" placeholder="Search users" /><Button type="submit">Search</Button></form>{error ? <EmptyState title="Users could not load" description={error.message} /> : users && users.length > 0 ? <div className="grid gap-4">{users.map((user) => <Card key={user.id}><CardContent className="grid gap-4 p-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="font-semibold">{user.full_name ?? user.email}</p><p className="text-sm text-muted-foreground">{user.email}</p></div><form action={updateUserRole} className="flex gap-2"><input name="user_id" type="hidden" value={user.id} /><select className="h-10 rounded-xl border border-input bg-background/60 px-3 text-sm" defaultValue={user.role} name="role"><option value="customer">Customer</option><option value="dealer">Dealer</option><option value="admin">Admin</option></select><SubmitButton pendingLabel="Saving..." size="sm">Save</SubmitButton></form></CardContent></Card>)}</div> : <EmptyState title="No users found" description="Matching profiles will appear here after signup." />}</div>; }
