import { EmptyState } from "@/components/app/empty-state";
import { MessageBanner } from "@/components/app/message-banner";
import { StatusBadge } from "@/components/app/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRole } from "@/lib/auth/guards";
import { listAccessibleDealerships } from "@/lib/bird-dog/dealer-data";
import { formatCurrency, formatDate, vehicleTitle } from "@/lib/bird-dog/format";
import type { RentalWithRelations } from "@/lib/bird-dog/types";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const metadata = { title: "Active rentals" };
export default async function DealerRentalsPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) { const params = await searchParams; const { user, profile } = await requireRole(["dealer", "admin"]); const supabase = await createServerSupabaseClient(); const { data: dealerships, error: dealershipError } = await listAccessibleDealerships(supabase, user.id, profile.role); const ids = dealerships.map((d) => d.id); if (dealershipError) return <EmptyState title="Rentals could not load" description={dealershipError.message} />; if (!ids.length) return <EmptyState title="No dealership assigned" description="Active rentals appear after dealership setup." />; const { data, error } = await supabase.from("rentals").select("*, vehicles (id, vin, year, make, model, trim, city, state), dealerships (id, name, phone), profiles (id, email, full_name, phone)").in("dealership_id", ids).eq("active", true).order("created_at", { ascending: false }); const rentals = (data ?? []) as RentalWithRelations[]; return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.32em] text-muted-foreground">Dealer fleet</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em]">Active rentals</h1><p className="mt-2 text-muted-foreground">Rentals converted from approved applications.</p></div><MessageBanner error={params.error} message={params.message} />{error ? <EmptyState title="Rentals could not load" description={error.message} /> : rentals.length === 0 ? <EmptyState description="Approved applications can be converted into active rentals from the application detail page." title="No active rentals" /> : <div className="grid gap-4">{rentals.map((rental) => <Card className="transition hover:border-white/20" key={rental.id}><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle>{rental.vehicles ? vehicleTitle(rental.vehicles) : "Vehicle unavailable"}</CardTitle><p className="text-sm text-muted-foreground">{rental.profiles?.full_name ?? rental.profiles?.email ?? "Customer"} · Starts {formatDate(rental.start_date)}</p></div><StatusBadge value={rental.active ? "rented" : "unavailable"} /></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><Info label="Monthly rate" value={formatCurrency(rental.monthly_rate)} /><Info label="Deposit" value={formatCurrency(rental.deposit)} /><Info label="End date" value={formatDate(rental.end_date)} /></CardContent></Card>)}</div>}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
