import { EmptyState } from "@/components/app/empty-state";
import { StatusBadge } from "@/components/app/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRole } from "@/lib/auth/guards";
import { formatCurrency, formatDate, vehicleTitle } from "@/lib/bird-dog/format";
import type { RentalWithRelations } from "@/lib/bird-dog/types";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const metadata = { title: "All rentals" };
export default async function AdminRentalsPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) { const params = await searchParams; await requireRole(["admin"]); const supabase = await createServerSupabaseClient(); let query = supabase.from("rentals").select("*, vehicles (id, vin, year, make, model, trim, city, state), dealerships (id, name, phone), profiles (id, email, full_name, phone)").order("created_at", { ascending: false }); if (params.q) query = query.or(`start_date.ilike.%${params.q}%,end_date.ilike.%${params.q}%`); const { data, error } = await query; const rentals = (data ?? []) as RentalWithRelations[]; return <div className="space-y-6"><div><h1 className="text-3xl font-bold">All rentals</h1><p className="mt-2 text-muted-foreground">Audit active and historical rental records.</p></div><Search value={params.q} />{error ? <EmptyState title="Rentals could not load" description={error.message} /> : rentals.length ? <div className="grid gap-4">{rentals.map((rental) => <Card key={rental.id}><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle>{rental.vehicles ? vehicleTitle(rental.vehicles) : "Vehicle unavailable"}</CardTitle><p className="text-sm text-muted-foreground">{rental.profiles?.email ?? "Customer"} · {rental.dealerships?.name ?? "Dealership"}</p></div><StatusBadge value={rental.active ? "rented" : "unavailable"} /></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><Info label="Monthly rate" value={formatCurrency(rental.monthly_rate)} /><Info label="Start" value={formatDate(rental.start_date)} /><Info label="End" value={formatDate(rental.end_date)} /></CardContent></Card>)}</div> : <EmptyState title="No rentals found" description="Rentals will appear after applications are converted." />}</div>; }
function Search({ value }: { value?: string }) { return <form className="flex gap-2"><input className="flex h-11 w-full rounded-xl border border-input bg-background/60 px-3 py-2 text-sm" defaultValue={value ?? ""} name="q" placeholder="Search dates" /><Button type="submit">Search</Button></form>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-border bg-background/40 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
