import Link from "next/link";
import type { Route } from "next";
import { EmptyState } from "@/components/app/empty-state";
import { StatusBadge } from "@/components/app/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRole } from "@/lib/auth/guards";
import { listAccessibleDealerships } from "@/lib/bird-dog/dealer-data";
import { formatCurrency, formatDate, vehicleTitle } from "@/lib/bird-dog/format";
import type { ApplicationWithRelations } from "@/lib/bird-dog/types";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const metadata = { title: "Applications" };
export default async function DealerApplicationsPage() { const { user, profile } = await requireRole(["dealer", "admin"]); const supabase = await createServerSupabaseClient(); const { data: dealerships, error: dealershipError } = await listAccessibleDealerships(supabase, user.id, profile.role); const ids = dealerships.map((d) => d.id); if (dealershipError) return <EmptyState title="Applications could not load" description={dealershipError.message} />; if (!ids.length) return <EmptyState action={<Button asChild><Link href="/dashboard/dealer/settings">Create dealership profile</Link></Button>} description="Applications appear after customers apply to your dealership vehicles." title="No dealership assigned" />; const { data, error } = await supabase.from("rental_applications").select("*, vehicles (id, vin, year, make, model, trim, monthly_price, deposit, city, state), dealerships (id, name, phone), profiles (id, email, full_name, phone), application_documents (id, application_id, document_type, file_url, created_at)").in("dealership_id", ids).order("created_at", { ascending: false }); const apps = (data ?? []) as ApplicationWithRelations[]; return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Applications inbox</h1><p className="mt-2 text-muted-foreground">Review customer applications for your dealership only.</p></div>{error ? <EmptyState title="Applications could not load" description={error.message} /> : apps.length === 0 ? <EmptyState description="Customer applications will appear here after public marketplace submissions." title="No applications yet" /> : <div className="grid gap-4">{apps.map((application) => <Card key={application.id}><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle>{application.vehicles ? vehicleTitle(application.vehicles) : "Vehicle unavailable"}</CardTitle><p className="text-sm text-muted-foreground">{application.profiles?.full_name ?? application.profiles?.email ?? "Customer"} · {formatDate(application.created_at)}</p></div><StatusBadge value={application.status} /></CardHeader><CardContent className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><p className="text-sm text-muted-foreground">{formatCurrency(application.vehicles?.monthly_price)}/mo · {application.application_documents.length} documents</p><Button asChild variant="outline"><Link href={`/dashboard/dealer/applications/${application.id}` as Route}>Review</Link></Button></CardContent></Card>)}</div>}</div>; }
