import Link from "next/link";
import type { Route } from "next";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRole } from "@/lib/auth/guards";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const metadata = { title: "Admin console" };
export default async function AdminDashboardPage() { await requireRole(["admin"]); const supabase = await createServerSupabaseClient(); const [users, dealerships, vehicles, applications, rentals] = await Promise.all([supabase.from("profiles").select("id", { count: "exact", head: true }), supabase.from("dealerships").select("id", { count: "exact", head: true }), supabase.from("vehicles").select("id", { count: "exact", head: true }), supabase.from("rental_applications").select("id", { count: "exact", head: true }), supabase.from("rentals").select("id", { count: "exact", head: true })]); return <div className="space-y-6"><section className="rounded-[2rem] border border-white/10 bg-card/85 p-7 shadow-2xl shadow-black/25 backdrop-blur-xl"><p className="text-xs font-semibold uppercase tracking-[0.32em] text-muted-foreground">Platform control</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em]">Admin dashboard</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">Approve dealerships and monitor real platform data.</p></section><div className="grid gap-4 md:grid-cols-5"><Metric label="Users" value={users.count ?? 0} /><Metric label="Dealerships" value={dealerships.count ?? 0} /><Metric label="Vehicles" value={vehicles.count ?? 0} /><Metric label="Applications" value={applications.count ?? 0} /><Metric label="Rentals" value={rentals.count ?? 0} /></div><div className="grid gap-4 sm:grid-cols-2"><Action href="/dashboard/admin/dealerships" title="Approve dealerships" /><Action href="/dashboard/admin/users" title="Manage users" /><Action href="/dashboard/admin/vehicles" title="View vehicles" /><Action href="/dashboard/admin/applications" title="View applications" /></div></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-4xl font-semibold tracking-[-0.05em]">{value}</p></CardContent></Card>; }
function Action({ href, title }: { href: Route; title: string }) { return <Card className="transition hover:-translate-y-0.5 hover:border-white/20"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><Button asChild><Link href={href}>{title}</Link></Button></CardContent></Card>; }
