import Link from "next/link";
import type { Route } from "next";
import { updateDealershipStatus } from "@/app/dashboard/admin/actions";
import { EmptyState } from "@/components/app/empty-state";
import { MessageBanner } from "@/components/app/message-banner";
import { StatusBadge } from "@/components/app/status-badge";
import { SubmitButton } from "@/components/forms/submit-button";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRole } from "@/lib/auth/guards";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const metadata = { title: "Dealership approvals" };
export default async function AdminDealershipsPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string; q?: string }> }) { const params = await searchParams; await requireRole(["admin"]); const supabase = await createServerSupabaseClient(); let query = supabase.from("dealerships").select("*").order("created_at", { ascending: false }); if (params.q) query = query.or(`name.ilike.%${params.q}%,city.ilike.%${params.q}%,state.ilike.%${params.q}%`); const { data: dealerships, error } = await query; return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Dealership approval</h1><p className="mt-2 text-muted-foreground">Approve, suspend, and inspect dealership accounts.</p></div><MessageBanner error={params.error} message={params.message} /><form className="flex gap-2"><input className="flex h-11 w-full rounded-xl border border-input bg-background/60 px-3 py-2 text-sm" defaultValue={params.q ?? ""} name="q" placeholder="Search dealerships" /><Button type="submit">Search</Button></form>{error ? <EmptyState title="Dealerships could not load" description={error.message} /> : dealerships && dealerships.length > 0 ? <div className="grid gap-4">{dealerships.map((dealership) => <Card key={dealership.id}><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle>{dealership.name}</CardTitle><p className="text-sm text-muted-foreground">{dealership.city}, {dealership.state}</p></div><StatusBadge value={dealership.suspended ? "suspended" : dealership.approved ? "approved" : "pending"} /></CardHeader><CardContent className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex flex-wrap gap-2"><StatusForm actionValue="approve" dealershipId={dealership.id} label="Approve" /><StatusForm actionValue="suspend" dealershipId={dealership.id} label="Suspend" /><StatusForm actionValue="unsuspend" dealershipId={dealership.id} label="Unsuspend" /></div><Button asChild variant="outline"><Link href={`/dashboard/admin/dealerships/${dealership.id}` as Route}>Details</Link></Button></CardContent></Card>)}</div> : <EmptyState title="No dealerships found" description="Dealership profiles will appear after dealer setup." />}</div>; }
function StatusForm({ actionValue, dealershipId, label }: { actionValue: string; dealershipId: string; label: string }) { return <form action={updateDealershipStatus}><input name="dealership_id" type="hidden" value={dealershipId} /><input name="action" type="hidden" value={actionValue} /><SubmitButton pendingLabel="Saving..." size="sm" variant="outline">{label}</SubmitButton></form>; }
