import { saveDealershipSettings } from "@/app/dashboard/dealer/actions";
import { MessageBanner } from "@/components/app/message-banner";
import { TextField } from "@/components/forms/form-field";
import { SubmitButton } from "@/components/forms/submit-button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRole } from "@/lib/auth/guards";
import { listAccessibleDealerships } from "@/lib/bird-dog/dealer-data";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const metadata = { title: "Dealership settings" };
export default async function DealerSettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) { const params = await searchParams; const { user } = await requireRole(["dealer"], "/dashboard/dealer/settings"); const supabase = await createServerSupabaseClient(); const { data: dealerships } = await listAccessibleDealerships(supabase, user.id); const dealership = dealerships[0]; return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.32em] text-muted-foreground">Dealer profile</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em]">Dealership settings</h1><p className="mt-2 text-muted-foreground">Manage the dealership profile used for marketplace listings.</p></div><MessageBanner error={params.error} message={params.message} /><Card className="border-white/15"><CardHeader><CardTitle>{dealership ? dealership.name : "Create dealership profile"}</CardTitle>{dealership ? <p className="text-sm text-muted-foreground">{dealership.approved ? "Approved for marketplace" : "Pending admin approval"}{dealership.suspended ? " · Suspended" : ""}</p> : null}</CardHeader><CardContent><form action={saveDealershipSettings} className="grid gap-5"><input name="dealership_id" type="hidden" value={dealership?.id ?? ""} /><div className="grid gap-4 md:grid-cols-2"><TextField defaultValue={dealership?.name ?? ""} label="Dealership name" name="name" required /><TextField defaultValue={dealership?.phone ?? ""} label="Phone" name="phone" /><TextField defaultValue={dealership?.website ?? ""} label="Website" name="website" /><TextField defaultValue={dealership?.address ?? ""} label="Address" name="address" /><TextField defaultValue={dealership?.city ?? ""} label="City" name="city" required /><TextField defaultValue={dealership?.state ?? ""} label="State" maxLength={2} name="state" required /><TextField defaultValue={dealership?.zip ?? ""} label="ZIP" name="zip" /></div><SubmitButton pendingLabel="Saving settings...">{dealership ? "Save dealership" : "Create dealership"}</SubmitButton></form></CardContent></Card></div>; }
